on:
  schedule:
  - cron: "5 * * * *"
jobs:
  achievement:
    runs-on: ubuntu-latest
    steps:
      - name: generate image 
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
      
