on:
  workflow_dispatch:
  schedule:
  - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
  push:
jobs:
  achievement:
    runs-on: ubuntu-latest
    name: Generate activity image 
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Generate"
        uses: lowlighter/metrics@latest
        with:
          
          name: Recently used
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.languages.recent.svg
            token: ${{ secrets.METRICS_TOKEN }}
              base: ""
              plugin_languages: yes

              plugin_languages_sections: recently-used
              plugin_languages_details: bytes-size, percentage
              plugin_languages_limit: 4

